// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EvalUIAction(arg1:main.UIAction):Promise<main.UIActionResult>;

export function SuggestCommand(arg1:string):Promise<Array<string>>;
