// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EvalUIAction(arg1) {
  return window['go']['main']['App']['EvalUIAction'](arg1);
}

export function SuggestCommand(arg1) {
  return window['go']['main']['App']['SuggestCommand'](arg1);
}
