// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EvalCommand(arg1:string):Promise<main.CommandResult>;

export function RowAction(arg1:Record<string, string>):Promise<main.CommandResult>;

export function SuggestCommand(arg1:string):Promise<Array<string>>;
